# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=400)),
                ('consignee', models.CharField(max_length=30)),
                ('consignee_tel', models.CharField(max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('postcode', models.CharField(max_length=6)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='goods/')),
            ],
            options={
                'db_table': 'Merchandise',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchan_num', models.IntegerField()),
                ('merchan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Merchandise')),
            ],
            options={
                'db_table': 'OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=20)),
                ('order_time', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('address_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Address')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='SalesNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('sales_num', models.IntegerField()),
                ('merchan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Merchandise')),
            ],
            options={
                'db_table': 'SalesNum',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30)),
                ('least_price', models.IntegerField()),
                ('deliver_fee', models.IntegerField()),
                ('review_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('shop_img', models.ImageField(upload_to='uploads/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Shop',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='shop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainpage.Shop'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Orders'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Shop'),
        ),
    ]
